#Always keep inventory on death on every dimension and world
alwaysKeepInventory = false
#Instead of keeping all inventory, only keep equipments, curios and quickbar tools on death
keepEquipments = true
#Fixes JEI and Bukkit server compat issue, don't touch unless you know what you are doing.
fixEssJeiIssue = true
#Range Detection tasks to execute per tick
#Range: 0.005 ~ 2.147483647E9
taskPerTick = 1.0
#Special array of players
"Player Whitelist" = ["YueSha", "duck_egg", "Evan", "dashuaibia", "khjxiaogu", "Lyuuke", "goumo_g", "Dev"]
#Temperature System difficulty
#Easy=Strong body
#Normal=Average
#Hard=Reality
#Hardcore=Sick body
#Allowed Values: Easy, Normal, Hard, HardCore
temperatureDifficulty = "Normal"
#Modifier of body temperature change speed, This does not affect hypothermia temperature.
#Range: 0.0 ~ 20.0
temperatureChangeRate = 0.5
#finalReducingValue = basicValue * waterReducingRate.(DoubleValue)
#Range: 0.0 ~ 1000.0
waterReducingRate = 1.0
#It is the weakness effect amplifier of the effect punishment when player's water level is too low. -1 means canceling this effect. Default:0
#Range: -1 ~ 999999
weaknessEffectAmplifier = 0
#It decides if players' water level would reset in death.
resetWaterLevelInDeath = true
#Enables snow accumulation during snow weather.
enableSnowAccumulationDuringWeather = true
#The the inverse of this value is the probability of snow adding one layer during each tick.
#Range: > 1
snowAccumulationDifficulty = 16
#Biomes that are not considered winter biomes.
nonWinterBiomes = ["minecraft:nether_wastes", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:basalt_deltas", "minecraft:soul_sand_valley", "minecraft:end_barrens", "minecraft:end_highlands", "minecraft:end_midlands", "minecraft:the_end", "minecraft:the_void", "terralith:yellowstone", "terralith:volcanic_crater", "terralith:volcanic_peaks", "terralith:caldera"]
#If true, the 'nonWinterBiomes' config option will be interpreted as a list of winter biomes, and all others will be ignored.
invertNonWinterBiomes = false

